"""
Generate a pre-filled bug report for the most recent call.

Usage:
    python src/generate_report.py [CALL_SID]

Reads call metadata from logs/last_call_meta.txt and the Twilio call record,
then writes a structured markdown report to reports/bug_report_<SID>.md.

Fill in the AGENT BEHAVIOR and BUGS FOUND sections after listening to the recording.
"""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
from twilio.rest import Client

load_dotenv()


def load_meta() -> dict:
    meta_file = Path("logs/last_call_meta.txt")
    if not meta_file.exists():
        return {}
    result = {}
    for line in meta_file.read_text().splitlines():
        if "=" in line:
            k, _, v = line.partition("=")
            result[k.strip()] = v.strip()
    return result


def main():
    sid = os.getenv("TWILIO_ACCOUNT_SID")
    token = os.getenv("TWILIO_AUTH_TOKEN")

    if len(sys.argv) > 1:
        call_sid = sys.argv[1].strip()
    else:
        sid_file = Path("logs/last_call_sid.txt")
        if not sid_file.exists():
            print("No call SID found. Run a scenario first or pass SID as argument.")
            raise SystemExit(1)
        call_sid = sid_file.read_text().strip()

    client = Client(sid, token)
    call = client.calls(call_sid).fetch()
    meta = load_meta()

    scenario = meta.get("scenario", "unknown")
    patient_name = meta.get("patient_name", "Unknown")
    dob = meta.get("dob", "Unknown")
    probe = meta.get("probe", "")
    description = meta.get("description", "")

    mp3_path = f"logs/recording_{call_sid}.mp3"
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    report = f"""# Bug Report — {scenario}

**Call SID**   : `{call_sid}`
**Date**       : {date_str}
**Scenario**   : {scenario}
**Patient**    : {patient_name} (DOB: {dob})
**Target**     : {call.to_formatted}
**Duration**   : {call.duration}s
**Recording**  : `{mp3_path}`

---

## Scenario Description

{description}

## What We Were Probing

{probe}

---

## Agent Behavior

> _Listen to `{mp3_path}` and fill in each section._

### Identity Verification
- [ ] Agent asked for patient name
- [ ] Agent asked for date of birth
- [ ] Agent confirmed identity before proceeding

**Notes:**
<!-- What did the agent actually say? Any issues? -->

### Scheduling Flow
- [ ] Agent asked for reason / how to help
- [ ] Agent offered appointment options
- [ ] Agent confirmed appointment details (date, time, provider)
- [ ] Agent provided a confirmation number or next steps

**Notes:**
<!-- Did the agent complete the booking? What was missing? -->

### Edge Case Handling
<!-- Scenario-specific: urgent care routing, insurance questions, specialist routing, etc. -->

**Notes:**

### Conversation Quality
- [ ] Agent maintained context across turns
- [ ] Agent re-prompted clearly when patient was unclear
- [ ] Agent did not repeat itself unnecessarily
- [ ] Agent ended the call politely

**Notes:**

---

## Bugs Found

<!-- Add one section per bug. Remove this block if no bugs found. -->

### BUG-001: [Short title]

| Field     | Value |
|-----------|-------|
| Severity  | High / Medium / Low |
| Category  | Verification / Scheduling / Routing / Conversation |
| Step      | Which part of the conversation |
| Expected  | What the agent should have done |
| Actual    | What the agent actually did |
| Timestamp | Approx. second in the recording |

---

### BUG-002: [Short title]

| Field     | Value |
|-----------|-------|
| Severity  |  |
| Category  |  |
| Step      |  |
| Expected  |  |
| Actual    |  |
| Timestamp |  |

---

## Positive Observations

<!-- Things the agent did correctly — useful for the balanced analysis in the README. -->

-
-

---

## Score

| Dimension                  | Result        |
|----------------------------|---------------|
| Identity Verification      | Pass / Fail / Partial |
| Appointment Completion     | Pass / Fail / Partial |
| Edge Case Handling         | Pass / Fail / N/A |
| Conversation Naturalness   | Pass / Fail / Partial |
| **Overall**                | **Pass / Fail** |

---

_Generated by generate_report.py — fill in AGENT BEHAVIOR and BUGS FOUND after listening to the recording._
"""

    Path("reports").mkdir(exist_ok=True)
    out_path = Path(f"reports/bug_report_{scenario}_{call_sid[:8]}.md")
    out_path.write_text(report)

    print(f"Report written → {out_path}")
    print(f"Recording     → {mp3_path}")
    print()
    print("Next steps:")
    print(f"  1. Play: explorer.exe {mp3_path}   (on WSL)")
    print(f"  2. Fill in:  {out_path}")


if __name__ == "__main__":
    main()
